server:
  port: 8001
spring:
  application:
    name: rabbitmq-producer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.56.100
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: TestHost
